from dotenv import load_dotenv
load_dotenv()

import os
import json

from langchain_core.tools import tool
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from langchain.agents import create_agent
from pydantic import BaseModel, Field

from data_extraction import get_weather_forecast

llm = ChatGoogleGenerativeAI(model='gemini-3.5-flash')

@tool
def outfit_recommender(location: str, hours: int) -> str:
    '''
    This function accepts the location and hours as input, and returns the weather forecast of that particular location for the entered number of hours.
    '''
    try:
        weather_forecast_dict = get_weather_forecast(location=location, hours=hours)
        weather_forecast_string = json.dumps(weather_forecast_dict)
        return weather_forecast_string
    except Exception as e:
        print(e)


system_message = '''
You are a smart outfit recommender assistant who recommends outfit based on the temperature forecast for next several hours.
1) Recommend an outfit that are easily available in average persons closet.
2) Recommend all the extra items that needs to be carried along with the outfit. for example - umbrella, sunglasses, hat/cap, etc
3) The whole outfit should be relevant. Do not recommend something like pair a leather jacket along with sleeping lower.
'''

class Output_format(BaseModel):
    weather_forecast_string: str = Field(description="The weather forecast output fetched from the get_weather_forecast function inside the output_recommender function")
    agent_recommendation: str = Field(description="This is the actual response generated by the LLM recommending a relevant outfut according to the weather forecast")


tools = [outfit_recommender]

agent = create_agent(
    model=llm,
    tools=tools,
    system_prompt=system_message,
    response_format=Output_format,
)

if __name__=="__main__":
    result = agent.invoke({
        "messages":[
            {
                "role":"user",
                "content":"I am going on a small hike in a small hilly area in Chuttupalu valley, Ramgarh Cantt, Jharkhand. The hike would be around 5 to 6 hours. Recommend an outfit that I should wear according to the weather forecast."
            }
        ]
    })
    print(result["structured_response"])




